# Generated by Django 4.0.3 on 2022-03-20 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0004_alter_task_notes'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToToList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todolist', models.CharField(max_length=200)),
            ],
        ),
    ]
