# Generated by Django 4.0.3 on 2022-03-20 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0005_totolist'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ToToList',
            new_name='ToDoList',
        ),
    ]
