# Generated by Django 4.0.3 on 2022-03-20 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todoapp', '0006_rename_totolist_todolist'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='todolist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todoapp.todolist'),
        ),
    ]
